name: "Setup Gradle"
description: "Setup Gradle and cache"

runs:
  using: "composite"
  steps:
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Cache gradle wrapper
      uses: actions/cache@v3
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-

    - name: Cache gradle build dir
      uses: actions/cache@v3
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/caches/transforms-*
          ~/.gradle/caches/modules-*
        key: ${{ runner.os }}-gradle-build-${{ github.job }}-${{ hashFiles('**/*.gradle.kts', 'gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-build-${{ github.job }}-
