name: "Setup Gradle"
description: "Setup Gradle and cache"
inputs:
  use-build-cache:
    description: 'Boolean value whether to use build cache'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 17
    - name: Cache gradle wrapper
      uses: actions/cache@v4
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/wrapper
        key: gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: gradle-wrapper-

    - name: Cache gradle dependencies dir
      uses: actions/cache@v4
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/transforms-*
          ~/.gradle/caches/modules-*
        key: gradle-dependencies-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: gradle-dependencies-
    - name: Cache gradle build results
      uses: actions/cache@v4
      if: ${{ inputs.use-build-cache == 'true' }}
      with:
        path: |
          .gradle
          ~/.gradle/caches/build-cache-*
          ~/.gradle/caches/[0-9]*.* # TODO: specify latest only
        key: gradle-build-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: gradle-build-cache-${{ runner.os }}-
