name: "Setup Gradle"
description: "Setup Gradle and cache"

runs:
  using: "composite"
  steps:
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - name: Cache gradle wrapper
      uses: actions/cache@v3
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-

    - name: Cache gradle dependencies dir
      uses: actions/cache@v3
      if: ${{ !startsWith(github.head_ref, 'renovate') }}
      with:
        path: |
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/transforms-*
          ~/.gradle/caches/modules-*
        key: ${{ runner.os }}-gradle-dependencies-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-dependencies-
    - name: Cache gradle build results
      uses: actions/cache@v3
      with:
        path: |
          .gradle
          ~/.gradle/caches/build-cache-*
          ~/.gradle/caches/[0-9]*.* # TODO: specify latest only
        key: gradle-build-cache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-gradle-build-cache-
