[versions]
aboutlibraries = "10.3.1"
accompanist = "0.23.1"
compose = "1.1.1"
hilt = "2.42"
ktor = "2.0.1"
room = "2.4.2"
kotlin = "1.6.10"
kotlin-compiler-extension = "1.1.1"
kotest = "5.3.0"
mockk = "1.12.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.4.1" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.4.2" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.1.1" }

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }

coil-compose = { module = "io.coil-kt:coil-compose", version = "2.1.0" }
firebase-core = { module = "com.google.firebase:firebase-core", version = "17.5.1" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "17.4.1" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.4.3" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.1.0" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

material = { module = "com.google.android.material:material", version = "1.6.0" }

okhttp-bom = "com.squareup.okhttp3:okhttp-bom:4.9.3"
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.4.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

hilt-android-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version = "7.2.0" }
license-tools-plugin = { module = "gradle.plugin.com.cookpad.android.plugin:plugin", version = "1.2.8" }
crashlytics-gradle-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.8.1" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
google-services-plugin = { module = "com.google.gms:google-services", version = "4.3.10" }
serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
aboutlibraries-plugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlibraries" }

aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version = "5.2.0" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

androidx-test-core = { module = "androidx.test:core", version = "1.4.0" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }