[versions]
compose = "1.0.5"
hilt = "2.40.4"
ktor = "1.5.1"
room = "2.4.0"
kotlin = "1.5.31"
kotlin-compiler-extension = "1.0.5"
kotest = "5.3.0"
mockk = "1.12.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version = "1.3.1" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "1.0.0-alpha07" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.4.2" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.1.1" }

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version = "0.22.0-rc" }

coil-compose = { module = "io.coil-kt:coil-compose", version = "1.4.0" }
firebase-core = { module = "com.google.firebase:firebase-core", version = "17.1.1" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "17.3.1" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.4.3" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.1.0" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization-jvm", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

material = { module = "com.google.android.material:material", version = "1.1.0" }

okhttp-bom = "com.squareup.okhttp3:okhttp-bom:4.9.1"
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.4.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
browser = { module = "androidx.browser:browser", version = "1.0.0" }
cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

hilt-android-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0-beta01" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version = "7.0.3" }
license-tools-plugin = { module = "gradle.plugin.com.cookpad.android.plugin:plugin", version = "1.2.8" }
crashlytics-gradle-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.2.0" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.27.0" }
google-services-plugin = { module = "com.google.gms:google-services", version = "4.3.8" }
serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

androidx-test-core = { module = "androidx.test:core", version = "1.4.0" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
robolectric = { module = "org.robolectric:robolectric", version = "4.0.2" }
junit = { module = "junit:junit", version = "4.12" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "3.12.0" }
mockito = { module = "org.mockito:mockito-core", version = "2.27.0" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }