default_platform :android

platform :android do
  before_all do
    # gradle(task: 'clean')
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :setup_for_ci do
    Dir.chdir('..') do
      sh('echo "API_KEY=\"$LAST_FM_API_KEY\"" >> local.properties')
      sh('echo "SHARED_SECRET=\"$LAST_FM_SHARED_SECRET\"" >> local.properties')
      sh('echo $GOOGLE_SERVICES_JSON > app/google-services.json')
    end
  end

  desc "Build an aab and run unit tests"
  lane :build_and_test do
    gradle(task: "bundleDebug")
    gradle(task: "testDebugUnitTest")
  end

  lane :debugbuild do
    gradle(task: 'assembleDebug')
  end

  lane :bundle_release do
    gradle(task: 'bundleRelease')
  end

  lane :fetch_metadata do
    download_from_play_store(
      package_name: 'com.mataku.scrobscrob'
    )
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "bundleRelease")
    supply(
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      track: 'internal'
    )
  end

  desc "Deploy a new version to the Google Play internal stage"
  lane :deploy_internal do
    gradle(task: "bundleRelease")
    supply(
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      track: 'internal',
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
