name: Architecture test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}-arch
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g"

jobs:
  arch_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'true'
      - uses: ./.github/actions/sunsetscrob-setup
        with:
          last-fm-api-key: ${{ secrets.LAST_FM_API_KEY }}
          last-fm-shared-secret: ${{ secrets.LAST_FM_SHARED_SECRET }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
      - name: Run architecture tests
        run: ./gradlew :architecture-spec:test
