name: Generate baseline profile

on:
  workflow_dispatch:
  schedule:
    - cron: '00 12 1 * *'

jobs:
  generate-baseline-profile:
    # ubuntu-latest is enough, but needed for Android Emulator: https://issuetracker.google.com/issues/193118030
    runs-on: macos-latest
    timeout-minutes: 25
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Cache gradle dir
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup
        env:
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          LAST_FM_SHARED_SECRET: ${{ secrets.LAST_FM_SHARED_SECRET }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
        run: |
          bundle exec fastlane android setup_for_ci
      - name: Generate benchmark profile
        run: |
          ./gradlew :benchmark:cleanManagedDevices --unused-only
          ./gradlew :benchmark:pixel4Api31BenchmarkAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
      - name: Move baseline profile file
        run: |
          mv benchmark/build/outputs/managed_device_android_test_additional_output/pixel4Api31/BaselineProfileGenerator_generateBaselineProfile-baseline-prof.txt app/src/main/baseline-prof.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Generate baseline profiles
          title: Generate baseline profiles
          body: Update baseline profiles by https://github.com/mataku/SunsetScrob/actions/workflows/baseline_profile.yml
          delete-branch: true
          branch: actions/update-baseline-profiles
          base: develop
          add-paths: |
            app/src/main
