# ref: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

name: cleanup all caches
on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 1 * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all caches
      run: |
        gh extension install actions/gh-actions-cache

        set +e
        gh actions-cache list -R $REPO -L 50 | cut -f 1 | sort | uniq | while IFS= read f
        do
          gh actions-cache delete $f -R $REPO --confirm
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
