name: Deploy to Google Play Console internal app sharing

on:
  workflow_dispatch:

concurrency:
  group: internal_app_sharing
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'false'

      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
      - name: Setup env
        env:
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          LAST_FM_SHARED_SECRET: ${{ secrets.LAST_FM_SHARED_SECRET }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
        run: |
          bundle exec fastlane android setup_for_ci
      - id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKFLOW_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: Prepare authentication
        run: |
          echo -n "${{ secrets.SUNSETSCROB_KEYSTORE }}" | base64 -d > SunsetScrob.jks
      - name: Generate benchmark profile
        env:
          SUNSET_KEY_ALIAS: ${{ secrets.SUNSET_KEY_ALIAS }}
          SUNSET_KEY_PASSWORD: ${{ secrets.SUNSET_KEY_PASSWORD }}
          SUNSET_STORE_PASSWORD: ${{ secrets.SUNSET_STORE_PASSWORD }}
        run: |
          ./gradlew cleanManagedDevices --unused-only
          ./gradlew app:generateReleaseBaselineProfile -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
      - name: Move baseline profile file
        run: |
          mv app/src/release/generated/baselineProfiles/baseline-prof.txt app/src/main/baseline-prof.txt
      - name: Deploy an aab
        env:
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          LAST_FM_SHARED_SECRET: ${{ secrets.LAST_FM_SHARED_SECRET }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SUNSET_KEY_ALIAS: ${{ secrets.SUNSET_KEY_ALIAS }}
          SUNSET_KEY_PASSWORD: ${{ secrets.SUNSET_KEY_PASSWORD }}
          SUNSET_STORE_PASSWORD: ${{ secrets.SUNSET_STORE_PASSWORD }}
        run: |
          bundle exec fastlane android deploy_internal_app_sharing
