name: Android Lint

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}-lint
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'true'
      - uses: ./.github/actions/sunsetscrob-setup
        with:
          last-fm-api-key: ${{ secrets.LAST_FM_API_KEY }}
          last-fm-shared-secret: ${{ secrets.LAST_FM_SHARED_SECRET }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
      - name: Run Android Lint
        run: ./gradlew :app:lintDebug
      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lint-reports
          path: |
            **/build/reports/lint-results-*.txt
            **/build/reports/lint-results-*.html
          if-no-files-found: ignore
