name: Run layout test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "develop"
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}-integration
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g"

jobs:
  screenshot_test:
    runs-on: macos-26
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'true'
      - uses: ./.github/actions/sunsetscrob-setup
        with:
          last-fm-api-key: ${{ secrets.LAST_FM_API_KEY }}
          last-fm-shared-secret: ${{ secrets.LAST_FM_SHARED_SECRET }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
      - name: Run screenshot tests
        run: ./gradlew verifyRoborazziJvm verifyRoborazziDebug --no-configuration-cache -PonlyScreenshotTest=true
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: android-test-reports
          path: |
            **/build/reports/roborazzi/**
            **/build/outputs/roborazzi/**
          retention-days: 7
