name: Build and test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'true'
      - uses: ./.github/actions/sunsetscrob-setup
        with:
          last-fm-api-key: ${{ secrets.LAST_FM_API_KEY }}
          last-fm-shared-secret: ${{ secrets.LAST_FM_SHARED_SECRET }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Setup signing config
        run: |
          echo -n "${{ secrets.SUNSETSCROB_KEYSTORE }}" | base64 -d > SunsetScrob.jks
          echo -n "${{ secrets.APP_PUBLISHER_JSON }}" | base64 -d > app/app-publisher.json
      - name: Build with Gradle
        env:
          SUNSET_KEY_ALIAS: ${{ secrets.SUNSET_KEY_ALIAS }}
          SUNSET_KEY_PASSWORD: ${{ secrets.SUNSET_KEY_PASSWORD }}
          SUNSET_STORE_PASSWORD: ${{ secrets.SUNSET_STORE_PASSWORD }}
        run: ./gradlew bundleRelease
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-gradle
        with:
          use-build-cache: 'true'
      - uses: ./.github/actions/sunsetscrob-setup
        with:
          last-fm-api-key: ${{ secrets.LAST_FM_API_KEY }}
          last-fm-shared-secret: ${{ secrets.LAST_FM_SHARED_SECRET }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}
      - name: Run tests
        run: ./gradlew testDebugUnitTest -PexcludeScreenshotTest=true
